// Homepage display data - categories, cities, featured
// All images stored locally in /public/images

export const HERO_IMAGE = "/images/hero/hero.jpg";

// Category name -> local image path
export const CATEGORY_IMAGES: Record<string, string> = {
  Vodoinstalater: "/images/categories/vodoinstalater.jpg",
  Električar: "/images/categories/elektricar.jpg",
  Keramičar: "/images/categories/keramicar.jpg",
  "Klima servis": "/images/categories/klima-servis.jpg",
  "Moler / gipsar": "/images/categories/moler-gipsar.jpg",
  Stolar: "/images/categories/stolar.jpg",
  Bravar: "/images/categories/bravar.jpg",
  Parketar: "/images/categories/parketar.jpg",
  "Fasade / izolacija": "/images/categories/fasade-izolacija.jpg",
  "Građevinski radovi": "/images/categories/gradjevinski-radovi.jpg",
  "Servis bojlera": "/images/categories/servis-bojlera.jpg",
  "Servis veš mašina": "/images/categories/servis-ves-masina.jpg",
  "Servis frižidera": "/images/categories/servis-frizidera.jpg",
  "Servis šporeta / rerne": "/images/categories/servis-sporeta-rerne.jpg",
  "Servis elektronike": "/images/categories/servis-elektronike.jpg",
  "Servis računara / laptopa": "/images/categories/servis-racunara-laptopa.jpg",
  "TV / antene / internet instalacije": "/images/categories/tv-antene-internet.jpg",
  "Montaža namještaja": "/images/categories/montaza-namjestaja.jpg",
  "Ugradnja kuhinja": "/images/categories/ugradnja-kuhinja.jpg",
  Čišćenje: "/images/categories/ciscenje.jpg",
  "Dubinsko čišćenje": "/images/categories/dubinsko-ciscenje.jpg",
  Selidbe: "/images/categories/selidbe.jpg",
  "Dvorište / bašta": "/images/categories/dvoriste-basta.jpg",
  "Roletne / tende": "/images/categories/roletne-tende.jpg",
  "Sitne kućne popravke": "/images/categories/sitne-kucne-popravke.jpg",
  "Alarm / video nadzor": "/images/categories/alarm-video-nadzor.jpg",
  "Brave / hitna otvaranja": "/images/categories/brave-hitna-otvaranja.jpg",
  "Solarni sistemi / paneli": "/images/categories/solarni-sistemi.jpg",
  "Gipsani radovi": "/images/categories/gipsani-radovi.jpg",
  "Sanacija vlage": "/images/categories/sanacija-vlage.jpg",
  "Odvoz šuta / otpada": "/images/categories/odvoz-suta-otpada.jpg",
  "Moler / sitne kućne popravke": "/images/categories/moler-sitne-kucne.jpg",
};

export const HOMEPAGE_CATEGORIES = [
  "Vodoinstalater",
  "Električar",
  "Klima servis",
  "Moler / sitne kućne popravke",
  "Montaža namještaja",
  "Čišćenje",
  "Selidbe",
  "Keramičar",
  "Servis bojlera",
  "Stolar",
  "Bravar",
  "Ugradnja kuhinja",
  "Dubinsko čišćenje",
  "Dvorište / bašta",
  "Sitne kućne popravke",
  "Alarm / video nadzor",
  "Parketar",
  "Fasade / izolacija",
  "Servis veš mašina",
  "Servis frižidera",
  "TV / antene / internet instalacije",
  "Gipsani radovi",
  "Sanacija vlage",
  "Roletne / tende",
  "Moler / gipsar",
  "Građevinski radovi",
  "Servis šporeta / rerne",
  "Servis elektronike",
  "Servis računara / laptopa",
  "Odvoz šuta / otpada",
  "Brave / hitna otvaranja",
  "Solarni sistemi / paneli",
];

export const HOMEPAGE_CITIES = [
  { name: "Podgorica", image: "/images/cities/podgorica.jpg" },
  { name: "Nikšić", image: "/images/cities/niksic.jpg" },
  { name: "Budva", image: "/images/cities/budva.jpg" },
  { name: "Bar", image: "/images/cities/bar.jpg" },
  { name: "Kotor", image: "/images/cities/kotor.jpg" },
  { name: "Herceg Novi", image: "/images/cities/herceg-novi.jpg" },
  { name: "Tivat", image: "/images/cities/tivat.jpg" },
  { name: "Cetinje", image: "/images/cities/cetinje.jpg" },
  { name: "Ulcinj", image: "/images/cities/ulcinj.jpg" },
  { name: "Bijelo Polje", image: "/images/cities/bijelo-polje.jpg" },
  { name: "Berane", image: "/images/cities/berane.jpg" },
  { name: "Pljevlja", image: "/images/cities/pljevlja.jpg" },
  { name: "Danilovgrad", image: "/images/cities/danilovgrad.jpg" },
  { name: "Kolašin", image: "/images/cities/kolasin.jpg" },
  { name: "Žabljak", image: "/images/cities/zabljak.jpg" },
];
