// Homepage display data - categories, cities, featured
// All images stored locally in /public/images

export const HERO_IMAGE = "/images/hero/hero-handyman.jpg";

// Category name -> local image path (actual work being done)
export const CATEGORY_IMAGES: Record<string, string> = {
  Vodoinstalater: "/images/categories/plumber.jpg",
  Električar: "/images/categories/electrician.jpg",
  Keramičar: "/images/categories/tiles.jpg",
  "Klima servis": "/images/categories/ac-technician.jpg",
  "Moler / gipsar": "/images/categories/painter.jpg",
  Stolar: "/images/categories/carpenter.jpg",
  Bravar: "/images/categories/locksmith.jpg",
  Parketar: "/images/categories/parquet.jpg",
  "Fasade / izolacija": "/images/categories/fasade.jpg",
  "Građevinski radovi": "/images/categories/construction.jpg",
  "Servis bojlera": "/images/categories/boiler.jpg",
  "Servis veš mašina": "/images/categories/washing-machine.jpg",
  "Servis frižidera": "/images/categories/refrigerator.jpg",
  "Servis šporeta / rerne": "/images/categories/oven.jpg",
  "Servis elektronike": "/images/categories/electronics.jpg",
  "Servis računara / laptopa": "/images/categories/laptop-repair.jpg",
  "TV / antene / internet instalacije": "/images/categories/tv-install.jpg",
  "Montaža namještaja": "/images/categories/furniture-assembly.jpg",
  "Ugradnja kuhinja": "/images/categories/kitchen-installation.jpg",
  Čišćenje: "/images/categories/cleaning.jpg",
  "Dubinsko čišćenje": "/images/categories/upholstery-cleaning.jpg",
  Selidbe: "/images/categories/movers.jpg",
  "Dvorište / bašta": "/images/categories/gardener.jpg",
  "Roletne / tende": "/images/categories/blinds.jpg",
  "Sitne kućne popravke": "/images/categories/handyman.jpg",
  "Alarm / video nadzor": "/images/categories/security-camera.jpg",
  "Brave / hitna otvaranja": "/images/categories/emergency-locksmith.jpg",
  "Solarni sistemi / paneli": "/images/categories/solar-panels.jpg",
  "Gipsani radovi": "/images/categories/plaster.jpg",
  "Sanacija vlage": "/images/categories/moisture.jpg",
  "Odvoz šuta / otpada": "/images/categories/waste.jpg",
  "Moler / sitne kućne popravke": "/images/categories/painter.jpg",
};

export const HOMEPAGE_CATEGORIES = [
  "Vodoinstalater",
  "Električar",
  "Klima servis",
  "Moler / sitne kućne popravke",
  "Montaža namještaja",
  "Čišćenje",
  "Selidbe",
  "Keramičar",
  "Servis bojlera",
  "Stolar",
  "Bravar",
  "Ugradnja kuhinja",
  "Dubinsko čišćenje",
  "Dvorište / bašta",
  "Sitne kućne popravke",
  "Alarm / video nadzor",
  "Parketar",
  "Fasade / izolacija",
  "Servis veš mašina",
  "Servis frižidera",
  "TV / antene / internet instalacije",
  "Gipsani radovi",
  "Sanacija vlage",
  "Roletne / tende",
  "Moler / gipsar",
  "Građevinski radovi",
  "Servis šporeta / rerne",
  "Servis elektronike",
  "Servis računara / laptopa",
  "Odvoz šuta / otpada",
  "Brave / hitna otvaranja",
  "Solarni sistemi / paneli",
];

export const HOMEPAGE_CITIES = [
  { name: "Podgorica", image: "/images/cities/podgorica.jpg" },
  { name: "Nikšić", image: "/images/cities/niksic.jpg" },
  { name: "Budva", image: "/images/cities/budva.jpg" },
  { name: "Bar", image: "/images/cities/bar.jpg" },
  { name: "Kotor", image: "/images/cities/kotor.jpg" },
  { name: "Herceg Novi", image: "/images/cities/herceg-novi.jpg" },
  { name: "Tivat", image: "/images/cities/tivat.jpg" },
  { name: "Cetinje", image: "/images/cities/cetinje.jpg" },
  { name: "Ulcinj", image: "/images/cities/ulcinj.jpg" },
  { name: "Bijelo Polje", image: "/images/cities/bijelo-polje.jpg" },
  { name: "Berane", image: "/images/cities/berane.jpg" },
  { name: "Pljevlja", image: "/images/cities/pljevlja.jpg" },
  { name: "Danilovgrad", image: "/images/cities/danilovgrad.jpg" },
  { name: "Kolašin", image: "/images/cities/kolasin.jpg" },
  { name: "Žabljak", image: "/images/cities/zabljak.jpg" },
];
